version: "3.8"

services:
  order-project:
    container_name: order-project
    build: 
      context: ./service
      dockerfile: Dockerfile.prod
    ports:
      - "8100:8100"
    volumes:
      - static_volume:/usr/src/prod/static
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    container_name: postgres-0
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pimat
      - POSTGRES_PASSWORD=pimat
      - POSTGRES_DB=order_db_prod

volumes:
  postgres_order_data_prod:
  static_volume: